import { Article, DailyBrief, UserProfile } from './types';

export const mockUser: UserProfile = {
  id: '1',
  name: 'Carry',
  email: 'carry@example.com',
  professionalIdentity: ['Medical Student', 'Researcher', 'Entrepreneur'],
  topics: ['Cardiology', 'Artificial Intelligence', 'Biomedical Engineering', 'Neuroscience'],
  goals: ['Research', 'Learning', 'Innovation'],
  informationDepth: ['Deep Research', 'Summary', 'News'],
};

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'AI ECG Foundation Model Achieves Cardiologist-Level Diagnosis',
    content: 'A new foundation model trained on 8.5 million ECGs from 2.1 million patients demonstrates unprecedented accuracy in detecting 77 cardiac conditions. The model, developed by a collaboration between Stanford and Google DeepMind, uses a novel temporal-spatial attention mechanism that processes raw 12-lead ECG signals without manual feature extraction...',
    summary: 'Stanford & Google DeepMind release an ECG foundation model trained on 8.5M ECGs achieving 94.2% accuracy across 77 conditions, outperforming board-certified cardiologists in 68 of them.',
    source: 'Nature Medicine',
    sourceType: 'arxiv',
    category: 'AI in Cardiology',
    importanceScore: 98,
    relevanceReason: 'Directly relevant to your ECG Simulator project and cardiology research interests.',
    recommendedAction: 'Read the methodology section on temporal-spatial attention. Consider integrating their preprocessing pipeline.',
    publishedAt: '2026-07-29T06:00:00Z',
    tags: ['ECG', 'Foundation Model', 'Cardiology', 'Deep Learning'],
    readTime: 12,
    isRead: false,
    isSaved: false,
  },
  {
    id: '2',
    title: 'FDA Clears First AI-Powered Continuous Cardiac Monitoring Wearable',
    content: 'The FDA has granted 510(k) clearance to CardioSense Pro, the first wearable device using on-device AI to continuously monitor and detect 12 types of cardiac arrhythmias in real-time...',
    summary: 'FDA clears CardioSense Pro for continuous AI cardiac monitoring, detecting 12 arrhythmia types with 96% sensitivity using edge AI processing.',
    source: 'MedTech Dive',
    sourceType: 'rss',
    category: 'Medical Devices',
    importanceScore: 91,
    relevanceReason: 'Relevant to your interests in cardiology and AI—shows regulatory pathway for AI cardiac devices.',
    recommendedAction: 'Review the FDA submission strategy for future reference on your own projects.',
    publishedAt: '2026-07-28T14:30:00Z',
    tags: ['FDA', 'Wearables', 'Cardiac Monitoring', 'Edge AI'],
    readTime: 6,
    isRead: false,
    isSaved: false,
  },
  {
    id: '3',
    title: 'Transformer Architecture Breakthrough: 10x Context Windows with Linear Complexity',
    content: 'Researchers at Anthropic have published a new attention mechanism that achieves 10x longer context windows while maintaining linear computational complexity...',
    summary: 'New linear-complexity attention mechanism enables 10M token context windows, potentially transforming how medical AI processes long patient records.',
    source: 'arXiv',
    sourceType: 'arxiv',
    category: 'Machine Learning',
    importanceScore: 85,
    relevanceReason: 'Could dramatically improve medical AI systems that need to process long patient histories.',
    recommendedAction: 'Skim abstract and implications section. Bookmark for deeper reading.',
    publishedAt: '2026-07-28T09:15:00Z',
    tags: ['Transformers', 'Attention', 'NLP', 'Efficiency'],
    readTime: 15,
    isRead: true,
    isSaved: true,
  },
  {
    id: '4',
    title: 'CRISPR-Cas13 Enables Programmable RNA Editing for Cardiac Gene Therapy',
    content: 'A team at the Broad Institute has demonstrated successful in vivo RNA editing using an enhanced CRISPR-Cas13 system in a mouse model of hypertrophic cardiomyopathy...',
    summary: 'Broad Institute achieves in vivo cardiac RNA editing with enhanced CRISPR-Cas13, reversing hypertrophic cardiomyopathy in mice with 73% efficiency.',
    source: 'Cell',
    sourceType: 'pubmed',
    category: 'Gene Therapy',
    importanceScore: 82,
    relevanceReason: 'Intersects your cardiology and biomedical engineering interests. Novel therapeutic approach.',
    recommendedAction: 'Save for your research notes on emerging cardiac therapies.',
    publishedAt: '2026-07-27T18:00:00Z',
    tags: ['CRISPR', 'Gene Therapy', 'Cardiology', 'RNA Editing'],
    readTime: 20,
    isRead: false,
    isSaved: false,
  },
  {
    id: '5',
    title: 'Y Combinator W26 Batch: 12 Healthcare AI Startups to Watch',
    content: 'The Winter 2026 Y Combinator batch included a record 12 healthcare AI startups. Here are the ones making waves...',
    summary: '12 healthcare AI startups from YC W26 batch, including 3 in cardiac diagnostics and 2 in AI-powered clinical trials.',
    source: 'TechCrunch',
    sourceType: 'rss',
    category: 'Startups & Innovation',
    importanceScore: 76,
    relevanceReason: 'Relevant to your entrepreneur identity. Competitive landscape for healthcare AI.',
    recommendedAction: 'Review the 3 cardiac diagnostics startups for potential collaboration or competitive analysis.',
    publishedAt: '2026-07-27T12:00:00Z',
    tags: ['Startups', 'YC', 'Healthcare AI', 'Entrepreneurship'],
    readTime: 8,
    isRead: false,
    isSaved: false,
  },
  {
    id: '6',
    title: 'Neural Interface Enables Direct Brain-to-Text Communication at 180 WPM',
    content: 'BrainGate consortium reports a neural interface achieving 180 words per minute brain-to-text conversion with 99.1% accuracy...',
    summary: 'BrainGate achieves 180 WPM brain-to-text with 99.1% accuracy using a new high-density electrode array and transformer decoder.',
    source: 'Science',
    sourceType: 'pubmed',
    category: 'Neuroscience',
    importanceScore: 72,
    relevanceReason: 'Aligns with your neuroscience topic interest. Demonstrates novel neural decoding architecture.',
    recommendedAction: 'Skim for cross-domain insights on signal processing techniques applicable to ECG.',
    publishedAt: '2026-07-26T20:00:00Z',
    tags: ['BCI', 'Neural Interface', 'Neuroscience', 'Signal Processing'],
    readTime: 14,
    isRead: false,
    isSaved: false,
  },
  {
    id: '7',
    title: 'Open-Source Medical LLM Outperforms GPT-4 on Clinical Reasoning Benchmarks',
    content: 'MedPaLM-Open, an open-source medical language model, has achieved state-of-the-art results on USMLE, MedQA, and clinical reasoning benchmarks...',
    summary: 'Open-source MedPaLM-Open achieves 92.4% on USMLE Step 1-3, surpassing GPT-4 by 3.2% while being fully reproducible.',
    source: 'arXiv',
    sourceType: 'arxiv',
    category: 'Medical AI',
    importanceScore: 88,
    relevanceReason: 'Open-source medical AI directly applicable to your research. Could be used in your projects.',
    recommendedAction: 'Download model weights and evaluate on your cardiac-specific test set.',
    publishedAt: '2026-07-28T11:00:00Z',
    tags: ['LLM', 'Medical AI', 'Open Source', 'Clinical Reasoning'],
    readTime: 10,
    isRead: false,
    isSaved: true,
  },
  {
    id: '8',
    title: 'Digital Twin Technology Reduces Clinical Trial Duration by 40%',
    content: 'Unlearn.AI reports that their digital twin platform reduced Phase III clinical trial duration by 40% while maintaining statistical power...',
    summary: 'Digital twin platform reduces Phase III trials by 40%, creating synthetic control arms that match real patient outcomes with 97% concordance.',
    source: 'STAT News',
    sourceType: 'newsletter',
    category: 'Clinical Trials',
    importanceScore: 68,
    relevanceReason: 'Relevant to your innovation goals. Novel application of AI in clinical research.',
    recommendedAction: 'Note the methodology for potential application in cardiac research.',
    publishedAt: '2026-07-26T08:00:00Z',
    tags: ['Digital Twins', 'Clinical Trials', 'Simulation', 'Innovation'],
    readTime: 7,
    isRead: true,
    isSaved: false,
  },
];

export const mockDailyBrief: DailyBrief = {
  greeting: 'Good morning, Carry.',
  date: new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
  highPriority: mockArticles.filter(a => a.importanceScore >= 85),
  stats: {
    newArticles: 24,
    highPriority: 4,
    savedItems: 12,
    sourcesActive: 18,
  },
};

export const mockCategories = [
  'All',
  'AI in Cardiology',
  'Machine Learning',
  'Medical Devices',
  'Gene Therapy',
  'Neuroscience',
  'Startups & Innovation',
  'Medical AI',
  'Clinical Trials',
];

export const profileOptions = {
  identities: [
    'Medical Student', 'Researcher', 'Entrepreneur', 'Engineer',
    'Clinician', 'Data Scientist', 'Product Manager', 'Biotech Professional',
  ],
  topics: [
    'Cardiology', 'Neuroscience', 'Artificial Intelligence', 'Biotechnology',
    'Genomics', 'Medical Devices', 'Drug Discovery', 'Public Health',
    'Radiology', 'Oncology', 'Digital Health', 'Robotics',
  ],
  goals: [
    'Learning', 'Research', 'Innovation', 'Business',
    'Clinical Practice', 'Teaching', 'Investing', 'Career Development',
  ],
  depths: [
    'News', 'Summary', 'Deep Research', 'Technical Papers',
  ],
};
