import { Article, DailyBrief, UserProfile } from './types';

export const mockUser: UserProfile = {
  id: '1',
  name: 'Carry',
  email: 'carry@example.com',
  professionalIdentity: ['Medical Student', 'Researcher', 'Entrepreneur'],
  topics: ['Cardiology', 'Artificial Intelligence', 'Biomedical Engineering', 'Neuroscience'],
  goals: ['Research', 'Learning', 'Innovation'],
  informationDepth: ['Deep Research', 'Summary', 'News'],
};

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'AI ECG Foundation Model Achieves Cardiologist-Level Diagnosis',
    content: `A new foundation model trained on 8.5 million ECGs from 2.1 million patients demonstrates unprecedented accuracy in detecting 77 cardiac conditions. The model, developed by a collaboration between Stanford and Google DeepMind, uses a novel temporal-spatial attention mechanism that processes raw 12-lead ECG signals without manual feature extraction.

The architecture builds on a modified vision transformer (ViT) adapted for 1D temporal signals. Each of the 12 leads is treated as a separate channel, and the model learns inter-lead relationships through cross-attention layers. The key innovation is the "temporal-spatial attention" block that simultaneously captures beat-to-beat morphology changes and spatial voltage gradients across leads.

Training used a two-stage approach: first, self-supervised pretraining on 6.2M unlabeled ECGs using a masked signal modeling objective (similar to MAE for images), followed by supervised fine-tuning on 2.3M labeled ECGs with multi-label classification heads for 77 conditions.

The model achieved an overall AUROC of 0.987 and accuracy of 94.2% across all 77 conditions. In head-to-head comparisons with 12 board-certified cardiologists, the model outperformed in 68 of 77 conditions, with the largest margins in subtle rhythm disorders and early-stage cardiomyopathies.

Notably, the model demonstrates strong zero-shot generalization to ECG devices not seen during training, suggesting that the learned representations capture fundamental cardiac electrophysiology rather than device-specific artifacts.`,
    summary: 'Stanford & Google DeepMind release an ECG foundation model trained on 8.5M ECGs achieving 94.2% accuracy across 77 conditions, outperforming board-certified cardiologists in 68 of them.',
    source: 'Nature Medicine',
    sourceType: 'arxiv',
    category: 'AI in Cardiology',
    importanceScore: 98,
    relevanceReason: 'Directly relevant to your ECG Simulator project and cardiology research interests.',
    recommendedAction: 'Read the methodology section on temporal-spatial attention. Consider integrating their preprocessing pipeline.',
    publishedAt: '2026-07-29T06:00:00Z',
    tags: ['ECG', 'Foundation Model', 'Cardiology', 'Deep Learning'],
    readTime: 12,
    isRead: false,
    isSaved: false,
  },
  {
    id: '2',
    title: 'FDA Clears First AI-Powered Continuous Cardiac Monitoring Wearable',
    content: 'The FDA has granted 510(k) clearance to CardioSense Pro, the first wearable device using on-device AI to continuously monitor and detect 12 types of cardiac arrhythmias in real-time. The device uses a proprietary edge AI chip that processes single-lead ECG signals at 500Hz with sub-second latency for arrhythmia detection.',
    summary: 'FDA clears CardioSense Pro for continuous AI cardiac monitoring, detecting 12 arrhythmia types with 96% sensitivity using edge AI processing.',
    source: 'MedTech Dive',
    sourceType: 'rss',
    category: 'Medical Devices',
    importanceScore: 91,
    relevanceReason: 'Relevant to your interests in cardiology and AI — shows regulatory pathway for AI cardiac devices.',
    recommendedAction: 'Review the FDA submission strategy for future reference on your own projects.',
    publishedAt: '2026-07-28T14:30:00Z',
    tags: ['FDA', 'Wearables', 'Cardiac Monitoring', 'Edge AI'],
    readTime: 6,
    isRead: false,
    isSaved: false,
  },
  {
    id: '3',
    title: 'Transformer Architecture Breakthrough: 10x Context Windows with Linear Complexity',
    content: 'Researchers at Anthropic have published a new attention mechanism that achieves 10x longer context windows while maintaining linear computational complexity. The approach, called "Cascading State Attention," uses a hierarchical state compression scheme that retains 99.3% of standard attention quality.',
    summary: 'New linear-complexity attention mechanism enables 10M token context windows, potentially transforming how medical AI processes long patient records.',
    source: 'arXiv',
    sourceType: 'arxiv',
    category: 'Machine Learning',
    importanceScore: 85,
    relevanceReason: 'Could dramatically improve medical AI systems that need to process long patient histories.',
    recommendedAction: 'Skim abstract and implications section. Bookmark for deeper reading.',
    publishedAt: '2026-07-28T09:15:00Z',
    tags: ['Transformers', 'Attention', 'NLP', 'Efficiency'],
    readTime: 15,
    isRead: true,
    isSaved: true,
  },
  {
    id: '4',
    title: 'CRISPR-Cas13 Enables Programmable RNA Editing for Cardiac Gene Therapy',
    content: 'A team at the Broad Institute has demonstrated successful in vivo RNA editing using an enhanced CRISPR-Cas13 system in a mouse model of hypertrophic cardiomyopathy. The approach achieved 73% editing efficiency with minimal off-target effects.',
    summary: 'Broad Institute achieves in vivo cardiac RNA editing with enhanced CRISPR-Cas13, reversing hypertrophic cardiomyopathy in mice with 73% efficiency.',
    source: 'Cell',
    sourceType: 'pubmed',
    category: 'Gene Therapy',
    importanceScore: 82,
    relevanceReason: 'Intersects your cardiology and biomedical engineering interests. Novel therapeutic approach.',
    recommendedAction: 'Save for your research notes on emerging cardiac therapies.',
    publishedAt: '2026-07-27T18:00:00Z',
    tags: ['CRISPR', 'Gene Therapy', 'Cardiology', 'RNA Editing'],
    readTime: 20,
    isRead: false,
    isSaved: false,
  },
  {
    id: '5',
    title: 'Y Combinator W26 Batch: 12 Healthcare AI Startups to Watch',
    content: 'The Winter 2026 Y Combinator batch included a record 12 healthcare AI startups spanning cardiac diagnostics, clinical trials, drug discovery, and remote patient monitoring.',
    summary: '12 healthcare AI startups from YC W26 batch, including 3 in cardiac diagnostics and 2 in AI-powered clinical trials.',
    source: 'TechCrunch',
    sourceType: 'rss',
    category: 'Startups & Innovation',
    importanceScore: 76,
    relevanceReason: 'Relevant to your entrepreneur identity. Competitive landscape for healthcare AI.',
    recommendedAction: 'Review the 3 cardiac diagnostics startups for potential collaboration or competitive analysis.',
    publishedAt: '2026-07-27T12:00:00Z',
    tags: ['Startups', 'YC', 'Healthcare AI', 'Entrepreneurship'],
    readTime: 8,
    isRead: false,
    isSaved: false,
  },
  {
    id: '6',
    title: 'Neural Interface Enables Direct Brain-to-Text Communication at 180 WPM',
    content: 'BrainGate consortium reports a neural interface achieving 180 words per minute brain-to-text conversion with 99.1% accuracy using a new high-density electrode array and transformer decoder.',
    summary: 'BrainGate achieves 180 WPM brain-to-text with 99.1% accuracy using a new high-density electrode array and transformer decoder.',
    source: 'Science',
    sourceType: 'pubmed',
    category: 'Neuroscience',
    importanceScore: 72,
    relevanceReason: 'Aligns with your neuroscience topic interest. Demonstrates novel neural decoding architecture.',
    recommendedAction: 'Skim for cross-domain insights on signal processing techniques applicable to ECG.',
    publishedAt: '2026-07-26T20:00:00Z',
    tags: ['BCI', 'Neural Interface', 'Neuroscience', 'Signal Processing'],
    readTime: 14,
    isRead: false,
    isSaved: false,
  },
  {
    id: '7',
    title: 'Open-Source Medical LLM Outperforms GPT-4 on Clinical Reasoning Benchmarks',
    content: 'MedPaLM-Open, an open-source medical language model, has achieved state-of-the-art results on USMLE, MedQA, and clinical reasoning benchmarks, scoring 92.4% on USMLE Step 1-3.',
    summary: 'Open-source MedPaLM-Open achieves 92.4% on USMLE Step 1-3, surpassing GPT-4 by 3.2% while being fully reproducible.',
    source: 'arXiv',
    sourceType: 'arxiv',
    category: 'Medical AI',
    importanceScore: 88,
    relevanceReason: 'Open-source medical AI directly applicable to your research. Could be used in your projects.',
    recommendedAction: 'Download model weights and evaluate on your cardiac-specific test set.',
    publishedAt: '2026-07-28T11:00:00Z',
    tags: ['LLM', 'Medical AI', 'Open Source', 'Clinical Reasoning'],
    readTime: 10,
    isRead: false,
    isSaved: true,
  },
  {
    id: '8',
    title: 'Digital Twin Technology Reduces Clinical Trial Duration by 40%',
    content: 'Unlearn.AI reports that their digital twin platform reduced Phase III clinical trial duration by 40% while maintaining statistical power, creating synthetic control arms with 97% concordance.',
    summary: 'Digital twin platform reduces Phase III trials by 40%, creating synthetic control arms that match real patient outcomes with 97% concordance.',
    source: 'STAT News',
    sourceType: 'newsletter',
    category: 'Clinical Trials',
    importanceScore: 68,
    relevanceReason: 'Relevant to your innovation goals. Novel application of AI in clinical research.',
    recommendedAction: 'Note the methodology for potential application in cardiac research.',
    publishedAt: '2026-07-26T08:00:00Z',
    tags: ['Digital Twins', 'Clinical Trials', 'Simulation', 'Innovation'],
    readTime: 7,
    isRead: true,
    isSaved: false,
  },
  {
    id: '9',
    title: 'Multi-Organ Bioprinting Achieves Vascularized Cardiac Tissue',
    content: 'ETH Zurich researchers demonstrate fully vascularized cardiac tissue patches using a novel multi-material bioprinting approach with patient-derived iPSCs.',
    summary: 'First vascularized cardiac tissue patches created via bioprinting using patient iPSCs, showing spontaneous beating and functional integration in rat models.',
    source: 'Nature Biotechnology',
    sourceType: 'pubmed',
    category: 'Biomedical Engineering',
    importanceScore: 79,
    relevanceReason: 'Directly relevant to your biomedical engineering interest. Represents a frontier in cardiac tissue engineering.',
    recommendedAction: 'Review the vascularization protocol — potential cross-application with your simulation work.',
    publishedAt: '2026-07-25T16:00:00Z',
    tags: ['Bioprinting', 'Tissue Engineering', 'iPSC', 'Cardiology'],
    readTime: 18,
    isRead: false,
    isSaved: false,
  },
  {
    id: '10',
    title: 'Federated Learning Framework Enables Cross-Hospital ECG Analysis Without Data Sharing',
    content: 'A consortium of 15 hospitals across 8 countries demonstrates that federated learning can train ECG analysis models matching centralized performance while keeping patient data local.',
    summary: '15-hospital federated learning study shows ECG models trained without data sharing achieve 98.7% of centralized model performance across arrhythmia detection.',
    source: 'The Lancet Digital Health',
    sourceType: 'pubmed',
    category: 'AI in Cardiology',
    importanceScore: 86,
    relevanceReason: 'Highly relevant to your ECG and AI interests. Solves a key data privacy challenge for medical AI deployment.',
    recommendedAction: 'Study the aggregation protocol — could inform your ECG Simulator data strategy.',
    publishedAt: '2026-07-27T07:00:00Z',
    tags: ['Federated Learning', 'ECG', 'Privacy', 'Multi-center'],
    readTime: 11,
    isRead: false,
    isSaved: true,
  },
  {
    id: '11',
    title: 'Apple Watch Series 12 Gains FDA Clearance for Continuous Blood Pressure Monitoring',
    content: 'Apple receives FDA clearance for continuous, cuffless blood pressure monitoring on Apple Watch Series 12, using photoplethysmography and on-device machine learning.',
    summary: 'Apple Watch Series 12 cleared for continuous cuffless BP monitoring — first consumer device with FDA clearance for this indication.',
    source: 'Bloomberg',
    sourceType: 'rss',
    category: 'Medical Devices',
    importanceScore: 74,
    relevanceReason: 'Consumer health tech reaching clinical grade. Relevant to wearable cardiac monitoring landscape.',
    recommendedAction: 'Track for competitive analysis with CardioSense Pro regulatory strategy.',
    publishedAt: '2026-07-26T14:00:00Z',
    tags: ['Apple Watch', 'Blood Pressure', 'Wearables', 'FDA'],
    readTime: 5,
    isRead: true,
    isSaved: false,
  },
  {
    id: '12',
    title: 'WHO Publishes Global Guidelines for AI in Clinical Decision Support',
    content: 'The World Health Organization releases comprehensive guidelines for the responsible development and deployment of AI-based clinical decision support systems.',
    summary: 'WHO guidelines establish a global framework for AI clinical decision support, covering validation, equity, transparency, and post-market surveillance.',
    source: 'WHO Bulletin',
    sourceType: 'newsletter',
    category: 'Regulation & Policy',
    importanceScore: 65,
    relevanceReason: 'Important context for any AI medical device you might develop. Shapes the regulatory landscape.',
    recommendedAction: 'Bookmark for reference when preparing regulatory submissions.',
    publishedAt: '2026-07-25T10:00:00Z',
    tags: ['WHO', 'Regulation', 'AI Policy', 'Clinical AI'],
    readTime: 9,
    isRead: false,
    isSaved: false,
  },
];

export const mockDailyBrief: DailyBrief = {
  greeting: 'Good morning, Carry.',
  date: new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
  highPriority: mockArticles.filter(a => a.importanceScore >= 85),
  stats: {
    newArticles: 24,
    highPriority: 5,
    savedItems: 12,
    sourcesActive: 18,
  },
};

export const mockTopicClusters = [
  { name: 'AI in Cardiology', count: 4, trend: +12, color: '#ef4444' },
  { name: 'Medical AI', count: 3, trend: +8, color: '#3b82f6' },
  { name: 'Machine Learning', count: 2, trend: +3, color: '#8b5cf6' },
  { name: 'Medical Devices', count: 2, trend: -2, color: '#22c55e' },
  { name: 'Gene Therapy', count: 1, trend: +5, color: '#f59e0b' },
  { name: 'Neuroscience', count: 1, trend: 0, color: '#06b6d4' },
];

export const mockWeeklyTrend = [
  { day: 'Mon', articles: 18, highPriority: 3 },
  { day: 'Tue', articles: 22, highPriority: 5 },
  { day: 'Wed', articles: 15, highPriority: 2 },
  { day: 'Thu', articles: 28, highPriority: 6 },
  { day: 'Fri', articles: 20, highPriority: 4 },
  { day: 'Sat', articles: 12, highPriority: 1 },
  { day: 'Sun', articles: 24, highPriority: 5 },
];

export const mockResearchHistory = [
  { id: '1', query: 'AI ECG diagnosis progress 2026', date: '2026-07-28', resultCount: 24 },
  { id: '2', query: 'CRISPR cardiac gene therapy mechanisms', date: '2026-07-25', resultCount: 18 },
  { id: '3', query: 'Federated learning in healthcare', date: '2026-07-22', resultCount: 31 },
];

export const mockNotes = [
  {
    id: 'n1',
    title: 'ECG Foundation Model — Integration Ideas',
    content: 'Consider adapting the temporal-spatial attention for our simulator. Key insight: self-supervised pretraining reduces annotation needs by 80%.',
    createdAt: '2026-07-29T08:00:00Z',
    tags: ['ECG', 'Ideas'],
    linkedArticleId: '1',
  },
  {
    id: 'n2',
    title: 'Regulatory Strategy Notes',
    content: 'FDA 510(k) pathway seems viable for our device class. CardioSense Pro clearance sets a predicate device precedent.',
    createdAt: '2026-07-28T16:00:00Z',
    tags: ['FDA', 'Strategy'],
    linkedArticleId: '2',
  },
  {
    id: 'n3',
    title: 'Research Proposal Draft: Federated ECG Learning',
    content: 'Proposal outline for multi-hospital ECG study using federated learning. Need to contact collaborators at Johns Hopkins and Mayo Clinic.',
    createdAt: '2026-07-27T10:00:00Z',
    tags: ['Research', 'Proposal'],
    linkedArticleId: '10',
  },
];

export const mockCategories = [
  'All',
  'AI in Cardiology',
  'Machine Learning',
  'Medical Devices',
  'Gene Therapy',
  'Neuroscience',
  'Startups & Innovation',
  'Medical AI',
  'Clinical Trials',
  'Biomedical Engineering',
  'Regulation & Policy',
];

export const profileOptions = {
  identities: [
    { label: 'Medical Student', description: 'Studying medicine, preparing for clinical practice' },
    { label: 'Researcher', description: 'Academic or industry research in biomedical sciences' },
    { label: 'Entrepreneur', description: 'Building or scaling a health/tech venture' },
    { label: 'Engineer', description: 'Developing medical devices, software, or systems' },
    { label: 'Clinician', description: 'Practicing physician or healthcare provider' },
    { label: 'Data Scientist', description: 'Working with medical data, ML models, analytics' },
    { label: 'Product Manager', description: 'Leading health tech product development' },
    { label: 'Biotech Professional', description: 'Working in biotechnology industry' },
  ],
  topics: [
    { label: 'Cardiology', description: 'Heart disease, ECG, interventional cardiology' },
    { label: 'Neuroscience', description: 'Brain research, neural interfaces, cognitive science' },
    { label: 'Artificial Intelligence', description: 'Machine learning, deep learning, LLMs' },
    { label: 'Biotechnology', description: 'Gene therapy, synthetic biology, bioprocessing' },
    { label: 'Genomics', description: 'DNA sequencing, genetic testing, precision medicine' },
    { label: 'Medical Devices', description: 'Wearables, diagnostics, surgical robotics' },
    { label: 'Drug Discovery', description: 'Pharma R&D, clinical trials, drug design' },
    { label: 'Public Health', description: 'Epidemiology, health systems, global health' },
    { label: 'Radiology', description: 'Medical imaging, AI-assisted diagnosis' },
    { label: 'Oncology', description: 'Cancer research, immunotherapy, screening' },
    { label: 'Digital Health', description: 'Telehealth, health apps, patient engagement' },
    { label: 'Robotics', description: 'Surgical robots, rehabilitation, automation' },
  ],
  goals: [
    { label: 'Learning', description: 'Stay current with the latest developments' },
    { label: 'Research', description: 'Find relevant papers and data for your work' },
    { label: 'Innovation', description: 'Discover new ideas and technologies' },
    { label: 'Business', description: 'Track market trends and opportunities' },
    { label: 'Clinical Practice', description: 'Apply new evidence to patient care' },
    { label: 'Teaching', description: 'Curate content for students and trainees' },
    { label: 'Investing', description: 'Evaluate health tech investment opportunities' },
    { label: 'Career Development', description: 'Build expertise and professional network' },
  ],
  depths: [
    { label: 'Headlines', description: 'Quick scan of what\'s happening' },
    { label: 'Summaries', description: 'AI-generated overviews of key findings' },
    { label: 'Deep Analysis', description: 'Structured reports with cross-source comparison' },
    { label: 'Technical Papers', description: 'Full academic papers with methodology details' },
  ],
};
