/**
 * Scan /content/{module}/*.json and generate src/content/generated-manifest.ts
 * so Next.js can statically import every record.
 */
import { readdir, writeFile, mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";

const ROOT = resolve(process.cwd());
const CONTENT = join(ROOT, "content");
const OUT = join(ROOT, "src/content/generated-manifest.ts");

const MODULES = [
  "focus",
  "questions",
  "projects",
  "concepts",
  "signals",
  "timeline",
] as const;

async function listJsonFiles(dir: string): Promise<string[]> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile() && e.name.endsWith(".json") && !e.name.startsWith("_"))
      .map((e) => e.name.replace(/\.json$/, ""))
      .sort();
  } catch {
    return [];
  }
}

function importName(module: string, slug: string): string {
  const safe = `${module}_${slug}`.replace(/[^a-zA-Z0-9_]/g, "_");
  return safe.replace(/^(\d)/, "_$1");
}

export async function generateContentManifest(): Promise<void> {
  const imports: string[] = [];
  const collections: Record<string, string[]> = {};

  for (const module of MODULES) {
    const slugs = await listJsonFiles(join(CONTENT, module));
    collections[module] = [];
    for (const slug of slugs) {
      const name = importName(module, slug);
      imports.push(
        `import ${name} from "../../content/${module}/${slug}.json";`,
      );
      collections[module].push(name);
    }
  }

  const body = `/**
 * AUTO-GENERATED by scripts/content/generate-manifest.ts
 * Do not edit by hand. Run: npm run content:manifest
 */

${imports.join("\n")}

import relationsCollection from "../../content/relations/edges.json";

function stripSchema<T extends Record<string, unknown>>(record: T): Omit<T, "$schema"> {
  const { $schema: _schema, ...rest } = record;
  return rest;
}

export const generatedFocus = [
${collections.focus.map((n) => `  stripSchema(${n}),`).join("\n")}
] as import("@/content/types").IntellectualFocusRecord[];

export const generatedQuestions = [
${collections.questions.map((n) => `  stripSchema(${n}),`).join("\n")}
] as import("@/content/types").ActiveQuestionRecord[];

export const generatedProjects = [
${collections.projects.map((n) => `  stripSchema(${n}),`).join("\n")}
] as import("@/content/types").ProjectRecord[];

export const generatedConcepts = [
${collections.concepts.map((n) => `  stripSchema(${n}),`).join("\n")}
] as import("@/content/types").ConceptRecord[];

export const generatedSignals = [
${collections.signals.map((n) => `  stripSchema(${n}),`).join("\n")}
] as import("@/content/types").SignalRecord[];

export const generatedTimeline = [
${collections.timeline.map((n) => `  stripSchema(${n}),`).join("\n")}
].sort((a, b) =>
  a.occurredAt.localeCompare(b.occurredAt),
) as import("@/content/types").TimelineEventRecord[];

export const generatedRelationsCollection =
  relationsCollection as import("@/content/types").RelationsCollection;
`;

  await mkdir(join(ROOT, "src/content"), { recursive: true });
  await writeFile(OUT, body, "utf8");
  console.log(
    `[content:manifest] wrote ${OUT} (${MODULES.map((m) => `${m}:${collections[m].length}`).join(", ")})`,
  );
}

const isDirectRun = process.argv[1]?.includes("generate-manifest");
if (isDirectRun) {
  generateContentManifest().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
