/**
 * AUTO-GENERATED by scripts/content/generate-manifest.ts
 * Do not edit by hand. Run: npm run content:manifest
 */

import focus_clinical_reasoning_ai from "../../content/focus/clinical-reasoning-ai.json";
import focus_ecg_simulator from "../../content/focus/ecg-simulator.json";
import focus_personal_knowledge_os from "../../content/focus/personal-knowledge-os.json";
import questions_clinical_reasoning_ai from "../../content/questions/clinical-reasoning-ai.json";
import questions_ecg_conduction from "../../content/questions/ecg-conduction.json";
import questions_mechanism_to_model from "../../content/questions/mechanism-to-model.json";
import projects_clinical_reasoning_ai from "../../content/projects/clinical-reasoning-ai.json";
import projects_ecg_simulator from "../../content/projects/ecg-simulator.json";
import projects_personal_knowledge_os from "../../content/projects/personal-knowledge-os.json";
import concepts_action_potential from "../../content/concepts/action-potential.json";
import concepts_ai from "../../content/concepts/ai.json";
import concepts_av_node from "../../content/concepts/av-node.json";
import concepts_biology from "../../content/concepts/biology.json";
import concepts_ecg_generation from "../../content/concepts/ecg-generation.json";
import concepts_human_systems from "../../content/concepts/human-systems.json";
import concepts_medicine from "../../content/concepts/medicine.json";
import concepts_neuroscience from "../../content/concepts/neuroscience.json";
import concepts_philosophy from "../../content/concepts/philosophy.json";
import concepts_sa_node from "../../content/concepts/sa-node.json";
import concepts_technology from "../../content/concepts/technology.json";
import signals_agentic_clinical_tutors from "../../content/signals/agentic-clinical-tutors.json";
import signals_cardiac_digital_twins from "../../content/signals/cardiac-digital-twins.json";
import signals_local_knowledge_graphs from "../../content/signals/local-knowledge-graphs.json";
import timeline_clinical_reasoning_ai_started from "../../content/timeline/clinical-reasoning-ai-started.json";
import timeline_ecg_simulator_started from "../../content/timeline/ecg-simulator-started.json";
import timeline_knowledge_os_initiated from "../../content/timeline/knowledge-os-initiated.json";
import timeline_mechanism_to_model_opened from "../../content/timeline/mechanism-to-model-opened.json";
import timeline_observatory_launched from "../../content/timeline/observatory-launched.json";

import relationsCollection from "../../content/relations/edges.json";

function stripSchema<T extends Record<string, unknown>>(record: T): Omit<T, "$schema"> {
  const { $schema: _schema, ...rest } = record;
  return rest;
}

export const generatedFocus = [
  stripSchema(focus_clinical_reasoning_ai),
  stripSchema(focus_ecg_simulator),
  stripSchema(focus_personal_knowledge_os),
] as import("@/content/types").IntellectualFocusRecord[];

export const generatedQuestions = [
  stripSchema(questions_clinical_reasoning_ai),
  stripSchema(questions_ecg_conduction),
  stripSchema(questions_mechanism_to_model),
] as import("@/content/types").ActiveQuestionRecord[];

export const generatedProjects = [
  stripSchema(projects_clinical_reasoning_ai),
  stripSchema(projects_ecg_simulator),
  stripSchema(projects_personal_knowledge_os),
] as import("@/content/types").ProjectRecord[];

export const generatedConcepts = [
  stripSchema(concepts_action_potential),
  stripSchema(concepts_ai),
  stripSchema(concepts_av_node),
  stripSchema(concepts_biology),
  stripSchema(concepts_ecg_generation),
  stripSchema(concepts_human_systems),
  stripSchema(concepts_medicine),
  stripSchema(concepts_neuroscience),
  stripSchema(concepts_philosophy),
  stripSchema(concepts_sa_node),
  stripSchema(concepts_technology),
] as import("@/content/types").ConceptRecord[];

export const generatedSignals = [
  stripSchema(signals_agentic_clinical_tutors),
  stripSchema(signals_cardiac_digital_twins),
  stripSchema(signals_local_knowledge_graphs),
] as import("@/content/types").SignalRecord[];

export const generatedTimeline = [
  stripSchema(timeline_clinical_reasoning_ai_started),
  stripSchema(timeline_ecg_simulator_started),
  stripSchema(timeline_knowledge_os_initiated),
  stripSchema(timeline_mechanism_to_model_opened),
  stripSchema(timeline_observatory_launched),
].sort((a, b) =>
  a.occurredAt.localeCompare(b.occurredAt),
) as import("@/content/types").TimelineEventRecord[];

export const generatedRelationsCollection =
  relationsCollection as import("@/content/types").RelationsCollection;
